# Generated by Django 5.1.2 on 2024-10-20 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_detail',
            name='number',
            field=models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
