# Generated by Django 5.1.2 on 2024-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_detail_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_detail',
            name='location',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
