# Generated by Django 5.1.2 on 2024-10-23 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_posts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='price',
            field=models.IntegerField(default=False, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
