# Generated by Django 5.1.2 on 2024-10-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_posts_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
