# Generated by Django 5.1.2 on 2024-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_post_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
