# Generated by Django 5.1.2 on 2024-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='accepter',
        ),
        migrations.AddField(
            model_name='post',
            name='creater',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
