# Generated by Django 5.1.2 on 2024-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_post_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.CharField(blank=True, default='post', max_length=50, null=True)),
                ('accepter', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='accepter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='requests',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='login.author'),
        ),
    ]
