# Generated by Django 5.1.2 on 2024-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_author_remove_post_accepter_remove_post_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='accepter',
        ),
        migrations.AddField(
            model_name='post',
            name='accepter',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
