# Generated by Django 5.1.2 on 2024-10-25 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_remove_author_accepter_post_accepter'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='requests',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='accepter',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='creater',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
