# Generated by Django 5.1.2 on 2024-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_author_status_alter_author_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='requests',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='accepter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='creater',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
