# Generated by Django 5.1.2 on 2024-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_author_requests_alter_post_accepter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='creater',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
    ]
