# Generated by Django 5.1.2 on 2024-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='datetime',
        ),
        migrations.AddField(
            model_name='room',
            name='dates',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='times',
            field=models.TimeField(auto_now=True),
        ),
    ]
