# Generated by Django 5.1.2 on 2024-11-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_remove_room_datetime_room_dates_room_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
