# Generated by Django 5.1.3 on 2024-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='login_detail',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
