# Generated by Django 5.1.3 on 2024-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_aadhaarverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarverification',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
