# Generated by Django 5.1.3 on 2024-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_aadhaarverification_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarverification',
            name='userid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
